[package]
name = "rusttest"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2.22", features = ["macros"] }
lambda_http = "0.1.1"
lambda_runtime = "0.2.1"
serde_json = "1.0.57"